name: krinry Build

on:
  workflow_dispatch:
    inputs:
      build_type:
        description: 'Build type'
        required: true
        default: 'release'
        type: choice
        options: [debug, profile, release]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.41.0'
          channel: 'stable'

      - name: Create android folder
        run: flutter create --platforms android .

      - name: Add Internet Permissions
        run: |
          MANIFEST="android/app/src/main/AndroidManifest.xml"
          sed -i 's|</manifest>|<uses-permission android:name="android.permission.INTERNET" />\n    <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />\n</manifest>|' $MANIFEST
          cat $MANIFEST

      - name: Pub get
        run: flutter pub get

      - name: Build APK (arm64 only)
        run: |
          TYPE="${{ github.event.inputs.build_type }}"
          flutter build apk --$TYPE --target-platform android-arm64

      - uses: actions/upload-artifact@v4
        with:
          name: build-output
          path: build/app/outputs/flutter-apk/app-release.apk
          retention-days: 7
